### ISSUE TITLE
Regular expression

### ISSUE THREAD

**Issue by famassar** [bloodiadotnet/Zabbix-Template-MD-Software-RAID#1]
Hi
In the readme you wrote: "Discovery of custom md different types as defined in global regular expression "Custom MD for discovery"
It's possible to have an example of this regexp?

Thanks!

**Comment by bloodiadotnet** [comment]
@famassar Sorry.
I created this repository a long time ago, so I don't remember much about its contents.

**Comment by famassar** [comment]
Thanks Anyway...
